apiVersion: run.tanzu.vmware.com/v1alpha1                   #TKG API endpoint
kind: TanzuKubernetesCluster                                #required parameter
metadata:
  name: tkc-1                                               #cluster name, user defined
spec:
  distribution:
    version: v1.19                                          #resolved kubernetes version v1.16.8
  topology:
    controlPlane:
      count: 1                                              #number of control plane nodes
      class: best-effort-xsmall                             #vmclass for control plane nodes
      storageClass: k8s-storage-policy                      #storageclass for control plane
      # volumes:
      #   - name: etcd
      #     mountPath: /var/lib/etcd
      #     capacity: 
      #       storage: 50Gi
    workers:
      count: 1                                              #number of worker nodes
      class: best-effort-xsmall                             #vmclass for worker nodes
      storageClass: k8s-storage-policy                      #storageclass for worker nodes
      # volumes:
      #   - name: containerd
      #     mountPath: /var/lib/containerd
      #     capacity: 
      #       storage: 100Gi