# This should work on Kubernetes deployments on AWS that have an ALB ingress controller deployed. 
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: yelb

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: yelb-pvc
  # namespace: yelb
  annotations:
    volume.beta.kubernetes.io/storage-class: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  # namespace: yelb
  labels:
    app: redis-server
    tier: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redis-server
    tier: cache
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-db
  # namespace: yelb
  labels:
    app: yelb-db
    tier: backenddb
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: yelb-db
    tier: backenddb
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
  # namespace: yelb
  labels:
    app: yelb-appserver
    tier: middletier
spec:
  type: ClusterIP
  ports:
  - port: 4567
  selector:
    app: yelb-appserver
    tier: middletier
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
  # namespace: yelb
  labels:
    app: yelb-ui
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: yelb-ui
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-ui
  # namespace: yelb
spec:
  selector:
    matchLabels:
      app: yelb-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: yelb-ui
        tier: frontend
    spec:
      containers:
      - name: yelb-ui
        image: harbor.ddmc.feg.com.tw/demo/yelb-ui:0.7
        ports:
        - containerPort: 80
        volumeMounts:
        - name: yelb-home
          mountPath: /home
      imagePullSecrets:
      - name: harbor
      volumes:
        - name: yelb-home
          persistentVolumeClaim:
            claimName: yelb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  # namespace: yelb
spec:
  selector:
    matchLabels:
      app: redis-server
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
        tier: cache
    spec:
      containers:
      - name: redis-server
        image: harbor.ddmc.feg.com.tw/demo/redis:latest
        ports:
        - containerPort: 6379
      imagePullSecrets:
      - name: harbor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-db
  # namespace: yelb
spec:
  selector:
    matchLabels:
      app: yelb-db
  replicas: 1
  template:
    metadata:
      labels:
        app: yelb-db
        tier: backenddb
    spec:
      containers:
      - name: yelb-db
        image:  harbor.ddmc.feg.com.tw/demo/yelb-db:0.5
        ports:
        - containerPort: 5432
      imagePullSecrets:
      - name: harbor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-appserver
  # namespace: yelb
spec:
  selector:
    matchLabels:
      app: yelb-appserver
  replicas: 1
  template:
    metadata:
      labels:
        app: yelb-appserver
        tier: middletier
    spec:
      containers:
      - name: yelb-appserver
        image:  harbor.ddmc.feg.com.tw/demo/yelb-appserver:0.5
        ports:
        - containerPort: 4567
      imagePullSecrets:
      - name: harbor
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "yelb-ui"
  # namespace: yelb
  labels:
    app: "yelb-ui"
spec:
  rules:
    - host: yelb.ddmc.lab
      http:
        paths:
        - backend:
            serviceName: "yelb-ui"
            servicePort: 80